#!/usr/bin/env python
# coding: utf-8



import pandas as pd
import re
import numpy as np

def give_bracket_contents (name_list, lower=True):
     """
  	Takes a list or series and returns the unique values in the brackets
  	
  	Parameters
  	----------
  	name_list: Series or array of Strings
  	lower: defines if returned list of strings is lowered
  
  	"""
    if type(name_list) == pd.core.series.Series:
        name_list = name_list.dropna().to_numpy()
    
    def zwischenklammer(string_content): 
        s = string_content
        result = re.search(r'\((.*?)\)',s)
        if result != None:
         return result.group(1)
    
    between_brackets = []
    for e in name_list:
        if e != None:
            between_brackets.append(zwischenklammer(e))

    seb = pd.Series(between_brackets)
    ergebnis = seb[between_brackets != np.array(None)].unique()
    if lower:
        ergebnis = [e.lower() for e in ergebnis]
    
    return ergebnis
